version: '3.8'

services:
  media-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Uncomment the following lines if you need to mount volumes
    # volumes:
    #   - ./data:/app/data
