# fly.toml app configuration file generated for mediathekcommunity on 2025-02-01T17:09:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mediathekcommunity'
primary_region = 'fra'

[build]
  [build.args]
    DIRECTUS_APIURL=""
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
